import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { GoogleAnalytics } from "@next/third-parties/google";

import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <!-- Google tag (gtag.js) -->  */}
      <GoogleAnalytics gaId="G-C3NK32E2TX" />
    </html>
  );
}
