import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< HEAD
=======
import { GoogleAnalytics } from "@next/third-parties/google"
>>>>>>> fe89115e7885ce53467a022bf75a3bb66ff6884f

import "./global.css";

const inter = Inter({ subsets: ["latin"] });

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

=======
>>>>>>> fe89115e7885ce53467a022bf75a3bb66ff6884f
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
<<<<<<< HEAD
=======
      {/*<!-- Google tag (gtag.js) -->*/}
      <GoogleAnalytics gaId="G-C3NK32E2TX"/>
>>>>>>> fe89115e7885ce53467a022bf75a3bb66ff6884f
    </html>
  );
}
